apiVersion: v1
kind: Service
metadata:
  name: mv
spec:
  selector:
    app.kubernetes.io/name: mv
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mv
  labels:
    app.kubernetes.io/name: mv
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mv
    spec:
      containers:
        - name: mv
          imagePullPolicy: Never
          image: local/mv:latest

