apiVersion: v1
kind: Pod
metadata:
  name: mv
  labels:
    app.kubernetes.io/name: mv
spec:
  containers:
    - name: mv
      imagePullPolicy: Never
      image: local/mv:latest
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mv
spec:
  selector:
    app.kubernetes.io/name: mv
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
