apiVersion: v1
kind: Service
metadata:
  name: mvtango
spec:
  selector:
    app.kubernetes.io/name: mvtango
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30002
      targetPort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvtango
  labels:
    app.kubernetes.io/name: mvtango
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mvtango
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mvtango
    spec:
      containers:
        - name: mv
          imagePullPolicy: Never
          image: local/mv:latest
          env:
            - name: USE_REDIS_FOR_STATE_SERVER
              value: "true"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: redis
          command: ['sh', '-c', 'serve_tango app -nodb --dlist mv/statemachine/1 -port 30002']
        - name: ping
          imagePullPolicy: Never
          image: local/mv:latest
          command: ['sh', '-c', 'sleep infinity']
---
apiVersion: v1
kind: Pod
metadata:
  name: ping
  labels:
    app.kubernetes.io/name: ping
spec:
  containers:
    - name: ping
      imagePullPolicy: Never
      env:
        - name: SERVER_IP
          value: mvtango
        - name: SERVER_PORT
          value: "80"
      image: local/mv:latest
      command: ['sh', '-c', 'sleep infinity']


